### ISSUE TITLE
[Get titles / Summary / Pause] - The app doesn't keep track of the offset in the summary after re-playing the summary

### ISSUE THREAD

**Issue by IlyaKnysh** [MozScout/scout-alexa#104]
1. Run the command "Alexa, ask Scout to Get titles"
2. Run the command "one"
3. Run the command "Summary"
4. Run the command "pause" during playback the summary
5. Repeat steps 1-4
6. Pay attention to a reproducible article

Actual result: The app doesn't keep track of the offset in the summary after re-playing the summary

Expected result: "Summary is played from a "Pause" place

**Comment by tamarahills** [comment]
Hi Ilya,

Yes, this is more by design actually.... Summary is usually so short we decided it was not worth tracking this.  Let's leave this open and will track as an enhancement.
