### ISSUE TITLE
Title/article mismatch

### ISSUE THREAD

**Issue by jrochell** [MozScout/scout-alexa#121]
Every time I tell Alexa to play a certain article (e.g. by saying “the 2nd one” or “the one about coffee”) it always reads a different, wrong title first. In my case, it says “The first white president” before reading the article I asked it to.

**Comment by tamarahills** [comment]
Hi @jrochell ,
Would you be able to give me an exact set of steps to repro this one?  i can't currently reproduce it.  Also, if you don't mind... there is an Alexa app (https://alexa.amazon.com/spa/index.html) if you can go to Settings|History it'll give a log of what you actually said (or at least what Alexa thinks you said ;) ).  

Also, helpful to know is this just on your account or others are experiencing this as well. 

Thanks,
-tamara

**Comment by jrochell** [comment]
Sure thing. Steps to reproduce: 

1. Ask Alexa to list my Pocket articles
2. Ask Alexa to play an article
3. The title of a different article is read, even though the correct article that I asked to listen to is played afterwards. 

My commands are quite simple and straightforward. 
<img width="266" alt="screenshot 2018-09-28 13 39 54" src="https://user-images.githubusercontent.com/1580471/46232421-08486000-c324-11e8-904a-27c197bbc59b.png">


This happens with every article I ask Alexa to read.

**Comment by jrochell** [comment]
Here's a recording of the issue in action

**Comment by jrochell** [comment]
(Sorry, I didn't see this comment above until now. 

I didn't clip the audio file. I did interrupt Alexa though - that's why she didn't get to the "what would you like to listen to" line. 

I reproduced the issue on October 2 at 1:44 pm PT. Please let me know if you need me to do it again.
