### ISSUE TITLE
CURRENTLY UNABLE TO REPRO:  CLOSE BY 10/5 -- When telling Alexa to read a new article, it continues reading the last one that wasn't completed

### ISSUE THREAD

**Issue by jrochell** [MozScout/scout-alexa#122]
I stopped playback, and later had Alexa read me my articles again. I asked her to play a different article, but Alexa resumed the article I was in the middle of listening from before, rather than the new one I asked her to read.

**Comment by tamarahills** [comment]
@jrochell Do you have the set of steps and exactly what you said on this one?  The Alexa app history would be great.  In particular, looking to see what you said when you stopped playback, what you said to have her read the articles again, what her response was.

Thanks,
-tamara

**Comment by tamarahills** [comment]
Per @jrochell, currently unable to repro.  Will leave this open for a week and close if we can't repro or find steps to repro.
