### ISSUE TITLE
Update commands with Pocket terminologies

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-alexa#126]
"Update commands with Pocket terminology: 
• In addition to ""titles"" allow for ""my list"", ""my articles"" and ""my saves"" E.g. ""Alexa, tell Pocket to get my articles""
• In additoin to ""get"" allow for ""read"" and ""play"" e.g. ""Alexa, tell Pocket to read my articles""
• Update commands in skill screen to reflect ""articles"" instead of ""titles"""

Need to make these changes in the model.

**Comment by HugoRomano** [comment]
Hey @tamarahills I've added another ask to this: In addition to "titles" we should also add "my stories" to the list. Also, ideally these would work with or without "my" at the beginning, so I could ask her: "Alexa tell pocket to get articles..." and also "Alexa tell pocket to get my articles..."

**Comment by dylano** [comment]
@HugoRomano You can take a look at at PR above to see the full list of utterances to trigger the article list -- let me know if any of those are unnecessary and I'll pull them out.
