### ISSUE TITLE
After "Alexa resume" prompt should be different

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-alexa#16]
Steps:
1.  Alexa, tell scout to get headlines
2.  Listen.
3.  Alexa pause
4.  Alexa resume
On resume it says: "here is the article <rest of article>".  We should say "continuing with your summary or continuing with your article.

**Comment by BScong** [comment]
We already got rid of the "Here is the article" prompt in #32 . So I guess there is nothing to do there?
