### ISSUE TITLE
After an article is finished playing, give a prompt to user

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-alexa#33]
Right now after an article is finished playing, there is dead air.

After the article ends, we should take them back up to the start state.

**Comment by tamarahills** [comment]
Let's just say "To listen to another article say Get Titles" for now and put them back in start state.

Eventually, we have to collect some feedback at this point.

**Comment by BScong** [comment]
Yeah It seems like we can't do that. We can't say prompts to the user after an audio event (PlaybackFinished), I gave more information in the PR and the Alexa documentation says that the response can't include outputSpeech (https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#playbackfinished)
