### ISSUE TITLE
Investigate play by number

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-alexa#41]
Right now we support 
"Play the one about"
"Play the article about"
And this maps to a Amazon.SearchQuery parameter.

See if we can support (in addition)
"Play the first article"
"Play article one"
"play one"

This may not work perfectly so we need to see what we can support.

**Comment by BScong** [comment]
So I think one way to do it is to create a Custom Slot Type with an enumeration detecting words like "first, second, number one, number two, one, two..." and linking them to ints (1, 2, ...) then set up samples as 

- "play the {ordinal} article"

- "play the {ordinal}"

- "play the article {ordinal}"

We would just have to check the slot type in the intent then fetch the int value and play the right article. If it is not in the enum then the classic AMAZON.SearchQuery will catch it.

What do you think? @tamarahills 

Docs : https://developer.amazon.com/docs/custom-skills/create-and-edit-custom-slot-types.html
