### ISSUE TITLE
Alexa says "to repeat the titles you just heard" and "repeating last titles" but repeats from the first titles

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-alexa#47]

**Comment by tamarahills** [comment]
@BScong Can you give set of steps to repro?

**Comment by BScong** [comment]
- Tell Scout to get titles
- Next
- Repeat

**Comment by dylano** [comment]
This seems to be working ok for me. With 9 or 10 articles in my account, I can say 'next' to get the second chunk of titles and repeat behaves as expected.

**Comment by BScong** [comment]
Mmh, so it is repeating the ones you just heard?
I have 6 articles. When I say Next, it gives me the title of my 6th article, but when I say Repeat, it gives me articles 1-5

**Comment by BScong** [comment]
Oh yeah you're right. It repeats articles 2-6. Sorry!
