### ISSUE TITLE
'Next' doesn't properly handle end of title list

### ISSUE THREAD

**Issue by dylano** [MozScout/scout-alexa#50]
If you are at the end of your list of titles and say "next", we don't notify the user that there are no more. The response is:
  "Here are the next titles:  . You can say play or summarize..."

We should say something along the lines of 
"there are no more titles. you can say 'repeat' or 'get titles' to go back to the beginning"

**Comment by BScong** [comment]
Isn't that the same problem as #46 ?

**Comment by dylano** [comment]
Yep, looks like it. Closing.
