### ISSUE TITLE
Add integration tests to Alexa Skill

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-alexa#57]

**Comment by BScong** [comment]
Tested https://github.com/ExpediaDotCom/alexa-conversation test framework. It doesn't work with the Alexa Progressive Response API so it crashes when it needs to do the synthesis. Everything before the synthesis works well however.

Note that if you want to test the Expedia Alexa Framework, you need to set the AWS_REGION env var (export AWS_REGION="us-east-1" or declare it in the code with aws-sdk). You also need to set all the environment variables from the Alexa lambda function in your system.
You also need to regenerate node_modules as they are compiled for Amazon Linux (keep the old one for when you upload)
For the params, set fixSpaces:true and accessToken to your Pocket id.

Also saw this other test framework https://github.com/BrianMacIntosh/alexa-skill-test-framework but it doesn't look like it supports Alexa Progressive Response API neither
