### ISSUE TITLE
In GetTitles, when user says Alexa Stop, we get an error saving state

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-alexa#62]
19:20:26
2018-06-01T19:20:26.476Z d682f70c-65d0-11e8-9962-5558dde2ac70 Error during DynamoDB put:ValidationException: One or more parameter values were invalid: An AttributeValue may not contain an empty string
2018-06-01T19:20:26.476Z d682f70c-65d0-11e8-9962-5558dde2ac70 Error during DynamoDB put:ValidationException: One or more parameter values were invalid: An AttributeValue may not contain an empty string

Most likely this is the cause: [](https://github.com/MozScout/scout-alexa/blob/master/lambda/custom/state_handlers.js#L214)

**Comment by tamarahills** [comment]
https://github.com/MozScout/scout-alexa/blob/master/lambda/custom/state_handlers.js#L214

**Comment by dylano** [comment]
Probably unrelated but a problem I just saw when testing this branch:

1. doliver: alexa, ask scout to play the article about california
2. alexa: summary or full article?
3. doliver: summary
4. alexa: *starts playing as exptected*
5. doliver: alexa, ask scout to get my titles
6. alexa: here are your titles: 1. ...
7. doliver: (while titles are playing) alexa, stop
8. alexa: goodbye, thanks for listening to the web
9. alexa: **resumes playing article about california**

**Comment by tamarahills** [comment]
It's not really unrelated, but it's not caused by this... I found this bug when trying to find a solution for the resuming playing article...

As far as the article resuming, still don't have a good solution for that.  That is #54.

**Comment by tamarahills** [comment]
If you look at my steps in #54, this eliminates the error message in step 4.

**Comment by tamarahills** [comment]
This is fixed by #85 

Closing.
