### ISSUE TITLE
Add some integration tests for the Alexa Lambda function

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-alexa#8]

**Comment by dylano** [comment]
Looking into a couple of mocha-friendly libraries to help with Alexa testing:
* alexa-conversation
  * this one has some trouble with DynamoDB, complaining about AWS region when instantiating table: "Missing region in config"
  * there is some discussion here and a possible resolution by using a local version of Dynamo: https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/134, https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/139
* virtual-alexa
   * https://github.com/bespoken/virtual-alexa
   * haven't tried this one yet, not sure if we'll hit the same DynamoDB issue

**Comment by dylano** [comment]
Got far enough with virtual-alexa to verify that it runs into the same Dynamo region config issue. Shelving this for now.
